"""Hydra/OmegaConf config utilities: MDP generation, config merging, saving."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

from omegaconf import DictConfig, OmegaConf

# ── MDP keyword mapping ────────────────────────────────────────────────
# Hydra config key (underscore) → GROMACS MDP keyword (may use hyphens)
# Only keys listed here are written to the .mdp file.
MDP_KEY_MAP: dict[str, str] = {
    "integrator":           "integrator",
    "dt":                   "dt",
    "nsteps":               "nsteps",
    "tcoupl":               "tcoupl",
    "tc_grps":              "tc-grps",
    "tau_t":                "tau-t",
    "ref_t":                "ref-t",
    "pcoupl":               "pcoupl",
    "pcoupltype":           "pcoupltype",
    "tau_p":                "tau-p",
    "ref_p":                "ref-p",
    "compressibility":      "compressibility",
    "cutoff_scheme":        "cutoff-scheme",
    "nstlist":              "nstlist",
    "rlist":                "rlist",
    "rcoulomb":             "rcoulomb",
    "rvdw":                 "rvdw",
    "coulombtype":          "coulombtype",
    "pme_order":            "pme-order",
    "fourierspacing":       "fourierspacing",
    "constraints":          "constraints",
    "constraint_algorithm": "constraint-algorithm",
    "lincs_iter":           "lincs-iter",
    "lincs_order":          "lincs-order",
    "nstxout":              "nstxout",
    "nstvout":              "nstvout",
    "nstfout":              "nstfout",
    "nstlog":               "nstlog",
    "nstxout_compressed":   "nstxout-compressed",
    "nstenergy":            "nstenergy",
}


def generate_mdp_from_config(
    cfg: DictConfig,
    output_path: str,
    extra_params: Optional[dict[str, Any]] = None,
) -> str:
    """Render a GROMACS .mdp file from the current Hydra config.

    Priority (highest→lowest): extra_params > method.nsteps > gromacs defaults.
    List values (tc_grps, tau_t, ref_t) are space-joined.

    Returns the output_path string.
    """
    gromacs_cfg: dict = OmegaConf.to_container(cfg.gromacs, resolve=True)

    # Method nsteps override
    if hasattr(cfg, "method") and OmegaConf.select(cfg, "method.nsteps") is not None:
        gromacs_cfg["nsteps"] = cfg.method.nsteps

    if extra_params:
        gromacs_cfg.update(extra_params)

    # Keep thermostat coupling robust across template/UI changes.
    # Using a single "System" group guarantees every atom belongs to a tc-grps entry.
    tcoupl = str(gromacs_cfg.get("tcoupl", "")).strip().lower()
    if tcoupl and tcoupl != "no":
        ref_t = gromacs_cfg.get("ref_t")
        tau_t = gromacs_cfg.get("tau_t")
        temp = gromacs_cfg.get("temperature", 300)
        ref_t0 = ref_t[0] if isinstance(ref_t, (list, tuple)) and ref_t else (ref_t if ref_t is not None else temp)
        tau_t0 = tau_t[0] if isinstance(tau_t, (list, tuple)) and tau_t else (tau_t if tau_t is not None else 0.1)
        gromacs_cfg["tc_grps"] = ["System"]
        gromacs_cfg["ref_t"] = [ref_t0]
        gromacs_cfg["tau_t"] = [tau_t0]

    lines = ["; Generated by md_agent — do not edit manually", ""]

    for hydra_key, mdp_key in MDP_KEY_MAP.items():
        val = gromacs_cfg.get(hydra_key)
        if val is None:
            continue
        if isinstance(val, (list, tuple)):
            val = " ".join(str(v) for v in val)
        lines.append(f"{mdp_key:<30} = {val}")

    # PLUMED methods must not write forces to trajectory.
    # plain / plain_md already have nstfout in MDP_KEY_MAP — skip to avoid duplicate.
    if (
        hasattr(cfg, "method")
        and OmegaConf.select(cfg, "method._target_name") not in (None, "plain", "plain_md")
    ):
        lines.append(f"{'nstfout':<30} = 0  ; PLUMED manages bias forces")

    content = "\n".join(lines) + "\n"
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content)
    return output_path


def config_from_extracted_settings(
    settings: dict[str, Any],
    base_cfg: DictConfig,
) -> DictConfig:
    """Merge extracted paper settings into a base Hydra config.

    Returns a new merged DictConfig (does not mutate base_cfg).
    """
    override: dict[str, Any] = {}

    if "gromacs" in settings and settings["gromacs"]:
        override["gromacs"] = settings["gromacs"]

    method = settings.get("method", "plain")
    plumed_params = settings.get("plumed", {})

    if method == "metadynamics":
        override["method"] = {
            "_target_name": "metadynamics",
            "hills": {
                "height": plumed_params.get("hills_height", 1.2),
                "sigma": plumed_params.get("hills_sigma", [0.35]),
                "pace": plumed_params.get("hills_pace", 500),
                "biasfactor": plumed_params.get("biasfactor"),
                "temp": settings.get("gromacs", {}).get(
                    "temperature", OmegaConf.select(base_cfg, "gromacs.temperature", default=300)
                ),
            },
        }
    elif method == "umbrella":
        override["method"] = {
            "_target_name": "umbrella_sampling",
            "restraint": {
                "force_constant": plumed_params.get("force_constant", 1000.0),
            },
        }
    elif method == "steered":
        override["method"] = {
            "_target_name": "steered_md",
            "pull": {
                "rate": plumed_params.get("pull_rate", 0.005),
                "force_constant": plumed_params.get("force_constant", 500.0),
            },
        }

    if "cvs" in plumed_params:
        override.setdefault("plumed", {})
        override["plumed"]["collective_variables"] = {"cvs": plumed_params["cvs"]}

    return OmegaConf.merge(base_cfg, OmegaConf.create(override))


def save_config(cfg_dict: dict[str, Any], output_path: str) -> str:
    """Save a config dict as a YAML file. Returns output_path."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(OmegaConf.to_yaml(OmegaConf.create(cfg_dict)))
    return str(path)


def load_config(config_path: str) -> dict[str, Any]:
    """Load a YAML config file and return as a plain dict."""
    cfg = OmegaConf.load(config_path)
    return OmegaConf.to_container(cfg, resolve=True)  # type: ignore[return-value]
